<?php

namespace AppBundle\Repository;

/**
 * TodoTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
